### ISSUE TITLE
What happens if album is not found?

### ISSUE THREAD

**Issue by booherbg** [RileyDu/milkcrate#2]
I added an album that is probably not on last.fm (sorry :P) and while the system reported a successful add, I believe it didn't make it to my milkcrate list (none are shown)

  - Album Title: "Christmas Crackers"
  - Artist: "The Disco Express"
  - Mood: "Upbeat"
  - Description: "Our early Christmas present to you. 🎄 A bumper fifteen track special, celebrating 3 years of XPRESS Edits."

**Comment by RileyDu** [comment]
I thought I had the bad response from Last.fm covered. It should be fully implemented now, with a placeholder img for the cover art. Before I had only tested it with title & artist being ‘asdf’, and technically that existed on last.fm just without a coverart image [just figured that out]. Now no matter what, if its on last.fm just without a coverart or it’s completely off last.fm[given data isn’t on last.fm] the placeholder should be defaulted for the cover art and the record should be added to the milkcrate fully. Tested it with your given data, and it goes through now. Eventually I want to enable image uploads for the coverart last.fm doesn’t have so the user can replace the placeholder with their desired image.
